/**
 * ExecuteListSettlementStatements - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListSettlementStatements Use Case
 *
 * DDD: Application use case for list Statement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListSettlementStatementsInput, ListSettlementStatementsOutput } from "../dto/statement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { StatementRepository } from "../ports";

export class ExecuteListSettlementStatements {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly statement: StatementRepository
  ) {}

  async execute(input: ListSettlementStatementsInput): Promise<ListSettlementStatementsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.statement.listSettlementStatements({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListSettlementStatementsOutput;
  }
}
