/**
 * Attachment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attachment DTOs
 *
 * DDD: Application DTOs for Attachment use cases.
 */

export type ListMeshAttachmentsInput = {};

export type ListMeshAttachmentsOutput = {};
