/**
 * Quarantine DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quarantine DTOs
 *
 * DDD: Application DTOs for Quarantine use cases.
 */

import type { QuarantineMeshNodeParams, QuarantineMeshNodeRequestInput } from "@hopsettle/core/topology/types";

export type ListQuarantineRecordsInput = {};

export type QuarantineMeshNodeInput = QuarantineMeshNodeParams & QuarantineMeshNodeRequestInput;

export type ListQuarantineRecordsOutput = {};

export type QuarantineMeshNodeOutput = {};
