/**
 * Snapshot DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Snapshot DTOs
 *
 * DDD: Application DTOs for Snapshot use cases.
 */

import type { GetTopologySnapshotParams } from "@hopsettle/core/topology/types";

export type GetTopologySnapshotInput = GetTopologySnapshotParams;

export type GetTopologySnapshotOutput = {};
