/**
 * ExecuteListPaymentChannels - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPaymentChannels Use Case
 *
 * DDD: Application use case for list Channel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPaymentChannelsInput, ListPaymentChannelsOutput } from "../dto/channel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { ChannelRepository } from "../ports";

export class ExecuteListPaymentChannels {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly channel: ChannelRepository
  ) {}

  async execute(input: ListPaymentChannelsInput): Promise<ListPaymentChannelsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.chnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.channel.listPaymentChannels({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPaymentChannelsOutput;
  }
}
