/**
 * ExecuteGetPaymentChannel - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPaymentChannel Use Case
 *
 * DDD: Application use case for get Channel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPaymentChannelInput, GetPaymentChannelOutput } from "../dto/channel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { ChannelRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPaymentChannel {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly channel: ChannelRepository
  ) {}

  async execute(input: GetPaymentChannelInput): Promise<GetPaymentChannelOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.chnId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).channelId) {
      throw new ValidationError("channelId is required");
    }
    const channelId = (input as any).channelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.channel.getPaymentChannel({ channelId: channelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${channelId}`);
    }

    return entity as GetPaymentChannelOutput;
  }
}
