/**
 * ExecuteDiscoverPaymentChannels - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDiscoverPaymentChannels Use Case
 *
 * DDD: Application use case for get Discovery.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DiscoverPaymentChannelsInput, DiscoverPaymentChannelsOutput } from "../dto/discovery.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { DiscoveryRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDiscoverPaymentChannels {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly discovery: DiscoveryRepository
  ) {}

  async execute(input: DiscoverPaymentChannelsInput): Promise<DiscoverPaymentChannelsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.chnId();

    // All field names extracted from OpenAPI spec: counterpartyMeshId, meshId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).counterpartyMeshId) {
      throw new ValidationError("counterpartyMeshId is required");
    }
    const counterpartymeshId = (input as any).counterpartyMeshId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.discovery.discoverPaymentChannels({ counterpartyMeshId: counterpartymeshId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${counterpartymeshId}`);
    }

    return entity as DiscoverPaymentChannelsOutput;
  }
}
