/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAccountingDomainModule,
  buildChannelsDomainModule,
  buildDisputesDomainModule,
  buildIdentityDomainModule,
  buildPricingDomainModule,
  buildReportingDomainModule,
  buildSettlementDomainModule,
  buildStakingDomainModule,
  buildTopologyDomainModule,
} from "../domains/index.js";
import type {
  AccountingDomainModule,
  ChannelsDomainModule,
  DisputesDomainModule,
  IdentityDomainModule,
  PricingDomainModule,
  ReportingDomainModule,
  SettlementDomainModule,
  StakingDomainModule,
  TopologyDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private accountingModule: AccountingDomainModule | null = null;
  private channelsModule: ChannelsDomainModule | null = null;
  private disputesModule: DisputesDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private pricingModule: PricingDomainModule | null = null;
  private reportingModule: ReportingDomainModule | null = null;
  private settlementModule: SettlementDomainModule | null = null;
  private stakingModule: StakingDomainModule | null = null;
  private topologyModule: TopologyDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get accounting domain module
   */
  getAccountingDependencies(): AccountingDomainModule {
    if (!this.accountingModule) {
      this.accountingModule = buildAccountingDomainModule(this.dynamoClient);
    }
    return this.accountingModule;
  }

  /**
   * Get channels domain module
   */
  getChannelsDependencies(): ChannelsDomainModule {
    if (!this.channelsModule) {
      this.channelsModule = buildChannelsDomainModule(this.dynamoClient);
    }
    return this.channelsModule;
  }

  /**
   * Get disputes domain module
   */
  getDisputesDependencies(): DisputesDomainModule {
    if (!this.disputesModule) {
      this.disputesModule = buildDisputesDomainModule(this.dynamoClient);
    }
    return this.disputesModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get pricing domain module
   */
  getPricingDependencies(): PricingDomainModule {
    if (!this.pricingModule) {
      this.pricingModule = buildPricingDomainModule(this.dynamoClient);
    }
    return this.pricingModule;
  }

  /**
   * Get reporting domain module
   */
  getReportingDependencies(): ReportingDomainModule {
    if (!this.reportingModule) {
      this.reportingModule = buildReportingDomainModule(this.dynamoClient);
    }
    return this.reportingModule;
  }

  /**
   * Get settlement domain module
   */
  getSettlementDependencies(): SettlementDomainModule {
    if (!this.settlementModule) {
      this.settlementModule = buildSettlementDomainModule(this.dynamoClient);
    }
    return this.settlementModule;
  }

  /**
   * Get staking domain module
   */
  getStakingDependencies(): StakingDomainModule {
    if (!this.stakingModule) {
      this.stakingModule = buildStakingDomainModule(this.dynamoClient);
    }
    return this.stakingModule;
  }

  /**
   * Get topology domain module
   */
  getTopologyDependencies(): TopologyDomainModule {
    if (!this.topologyModule) {
      this.topologyModule = buildTopologyDomainModule(this.dynamoClient);
    }
    return this.topologyModule;
  }

  clearAccountingDependencies(): void { this.accountingModule = null; }
  clearChannelsDependencies(): void { this.channelsModule = null; }
  clearDisputesDependencies(): void { this.disputesModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearPricingDependencies(): void { this.pricingModule = null; }
  clearReportingDependencies(): void { this.reportingModule = null; }
  clearSettlementDependencies(): void { this.settlementModule = null; }
  clearStakingDependencies(): void { this.stakingModule = null; }
  clearTopologyDependencies(): void { this.topologyModule = null; }

  getAccountingDependenciesForRequest(): AccountingDomainModule {
    return this.getAccountingDependencies();
  }

  getChannelsDependenciesForRequest(): ChannelsDomainModule {
    return this.getChannelsDependencies();
  }

  getDisputesDependenciesForRequest(): DisputesDomainModule {
    return this.getDisputesDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getPricingDependenciesForRequest(): PricingDomainModule {
    return this.getPricingDependencies();
  }

  getReportingDependenciesForRequest(): ReportingDomainModule {
    return this.getReportingDependencies();
  }

  getSettlementDependenciesForRequest(): SettlementDomainModule {
    return this.getSettlementDependencies();
  }

  getStakingDependenciesForRequest(): StakingDomainModule {
    return this.getStakingDependencies();
  }

  getTopologyDependenciesForRequest(): TopologyDomainModule {
    return this.getTopologyDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.accountingModule = null;
    this.channelsModule = null;
    this.disputesModule = null;
    this.identityModule = null;
    this.pricingModule = null;
    this.reportingModule = null;
    this.settlementModule = null;
    this.stakingModule = null;
    this.topologyModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
