/**
 * GetSnapshot DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetTopologySnapshotParams } from "@hopsettle/core/topology";

export function createGetSnapshotRequest(overrides: Partial<GetTopologySnapshotParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
