/**
 * ExecutePreviewPathCharges - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePreviewPathCharges Use Case
 *
 * DDD: Application use case for get PathPreview.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PreviewPathChargesInput, PreviewPathChargesOutput } from "../dto/path-preview.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { PathPreviewRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePreviewPathCharges {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pathPreview: PathPreviewRepository
  ) {}

  async execute(input: PreviewPathChargesInput): Promise<PreviewPathChargesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prcId();

    // All field names extracted from OpenAPI spec: bytes, meshAttachmentId, policyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).meshAttachmentId) {
      throw new ValidationError("meshAttachmentId is required");
    }
    const meshattachmentId = (input as any).meshAttachmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.pathPreview.previewPathCharges({ meshAttachmentId: meshattachmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${meshattachmentId}`);
    }

    return entity as PreviewPathChargesOutput;
  }
}
