/**
 * ExecuteCreatePricingPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePricingPolicy Use Case
 *
 * DDD: Application use case for create Policy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePricingPolicyInput, CreatePricingPolicyOutput } from "../dto/policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { PolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePricingPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policy: PolicyRepository
  ) {}

  async execute(input: CreatePricingPolicyInput): Promise<CreatePricingPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prcId();

    // All field names extracted from OpenAPI spec: effectiveAt, meshAttachmentId, pricePerUnit, relaySharePercent, role, superpeerMarkupPercent, unit
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }
    if (!input.pricePerUnit) {
      throw new ValidationError("pricePerUnit is required");
    }
    if (!input.unit) {
      throw new ValidationError("unit is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (pricing domain)
    const entityId = this.idGenerator.prcId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.policy.createPricingPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePricingPolicyOutput;
  }
}
