/**
 * AttachmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttachmentRepository Port
 *
 * DDD: Application port for attachmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListMeshAttachmentsInput, ListMeshAttachmentsOutput } from "../dto/attachment.dto";
export interface AttachmentRepository {
  listMeshAttachments(input: ListMeshAttachmentsInput): Promise<ListMeshAttachmentsOutput>;
}

export type { ListMeshAttachmentsInput, ListMeshAttachmentsOutput } from "../dto/attachment.dto";
