/**
 * SnapshotRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SnapshotRepository Port
 *
 * DDD: Application port for snapshotrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTopologySnapshotInput, GetTopologySnapshotOutput } from "../dto/snapshot.dto";
export interface SnapshotRepository {
  getTopologySnapshot(input: GetTopologySnapshotInput): Promise<GetTopologySnapshotOutput>;
}

export type { GetTopologySnapshotInput, GetTopologySnapshotOutput } from "../dto/snapshot.dto";
