/**
 * Routes for AccountingEntry
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { ingestAccountingEntry, listAccountingEntries } from "../handlers/accounting-entry.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function accountingEntryRoutes(fastify: FastifyInstance) {
  // POST /v1/accounting/entries (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/accounting/entries",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAccountingDependenciesForRequest();
        await ingestAccountingEntry(request, reply, deps);
      });
    }
  );


  // GET /v1/accounting/entries (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/accounting/entries",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAccountingDependenciesForRequest();
        await listAccountingEntries(request, reply, deps);
      });
    }
  );


}
