/**
 * Dispute DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Dispute DTOs
 *
 * DDD: Application DTOs for Dispute use cases.
 */

import type { CreateDisputeRequestInput, GetDisputeParams, ListDisputesParams } from "@hopsettle/core/disputes/types";

export type ListDisputesInput = ListDisputesParams;

export type CreateDisputeInput = CreateDisputeRequestInput;

export type GetDisputeInput = GetDisputeParams;

export type ListDisputesOutput = {};

export type CreateDisputeOutput = {};

export type GetDisputeOutput = {};
