/**
 * TopUpRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TopUpRepository Port
 *
 * DDD: Application port for topuprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordStakingTopUpInput, RecordStakingTopUpOutput } from "../dto/top-up.dto";
export interface TopUpRepository {
  recordStakingTopUp(input: RecordStakingTopUpInput): Promise<RecordStakingTopUpOutput>;
}

export type { RecordStakingTopUpInput, RecordStakingTopUpOutput } from "../dto/top-up.dto";
