/**
 * Handlers for Alert
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { StakingDomainModule } from "../dependencies/staking-ddd.dependencies.js";
import type { ListFloatAlertsInput } from "@hopsettle/services/staking";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/staking/accounts/{meshId}/alerts
 * Operation: listFloatAlerts
 */
export async function listFloatAlerts(
  request: FastifyRequest<{ Params: { meshId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StakingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListFloatAlertsInput = {
    meshId: request.params.meshId,
  };
  const result = await deps.useCases.alerts.list.execute(input);
  return reply.code(200).send(result);
}


