/**
 * GetTopologySnapshot handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTopologySnapshot } from "@hopsettle/api-server/domains/topology/handlers";
import type { TopologyDDDDependencies } from "@hopsettle/api-server/domains/topology";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@hopsettle/tests/shared";
import { TOPOLOGY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTopologySnapshot", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TopologyDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TopologyDDDDependencies>(
      TOPOLOGY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTopologySnapshot, "execute").mockResolvedValue(useCaseResult);

    await getTopologySnapshot(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTopologySnapshot.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
