/**
 * Routes for Policy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPricingPolicy, getPricingPolicy, listPricingPolicies } from "../handlers/policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function policyRoutes(fastify: FastifyInstance) {
  // POST /v1/pricing/policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/pricing/policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPricingDependenciesForRequest();
        await createPricingPolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/pricing/policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pricing/policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPricingDependenciesForRequest();
        await listPricingPolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/pricing/policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pricing/policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPricingDependenciesForRequest();
        await getPricingPolicy(request, reply, deps);
      });
    }
  );


}
