/**
 * ExecuteExportDisputeEvidence - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExportDisputeEvidence Use Case
 *
 * DDD: Application use case for list EvidenceExport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExportDisputeEvidenceInput, ExportDisputeEvidenceOutput } from "../dto/evidence-export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { EvidenceExportRepository } from "../ports";

export class ExecuteExportDisputeEvidence {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidenceExport: EvidenceExportRepository
  ) {}

  async execute(input: ExportDisputeEvidenceInput): Promise<ExportDisputeEvidenceOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dspId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.evidenceExport.exportDisputeEvidence({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ExportDisputeEvidenceOutput;
  }
}
