/**
 * EvidenceExportRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidenceExportRepositoryDdb
 *
 * DDD: Infrastructure adapter for EvidenceExport repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { EvidenceExportRepository } from "@hopsettle/services/disputes";

export class EvidenceExportRepositoryDdb implements EvidenceExportRepository {
  constructor(private readonly dynamoClient: any) {}

  async exportDisputeEvidence(input: Parameters<EvidenceExportRepository['exportDisputeEvidence']>[0]): Promise<Awaited<ReturnType<EvidenceExportRepository['exportDisputeEvidence']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
