/**
 * QuarantineRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QuarantineRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements QuarantineRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  QuarantineRepository,
} from "@hopsettle/services/topology";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { QuarantineRepositoryDdb } from "./quarantine-repository.ddb.js";

/**
 * QuarantineRepositoryAdapter
 *
 * Implements QuarantineRepository port for infrastructure layer.
 */
export class QuarantineRepositoryAdapter implements QuarantineRepository {
  private readonly ddb: QuarantineRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new QuarantineRepositoryDdb(this.dynamoClient);
  }

  async listQuarantineRecords(input: Parameters<QuarantineRepository['listQuarantineRecords']>[0]): Promise<Awaited<ReturnType<QuarantineRepository['listQuarantineRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listQuarantineRecords(input);
  }

  async quarantineMeshNode(input: Parameters<QuarantineRepository['quarantineMeshNode']>[0]): Promise<Awaited<ReturnType<QuarantineRepository['quarantineMeshNode']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.quarantineMeshNode(input);
  }
}
