/**
 * ChannelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChannelRepository Port
 *
 * DDD: Application port for channelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPaymentChannelInput, GetPaymentChannelOutput, ListPaymentChannelsInput, ListPaymentChannelsOutput, OpenPaymentChannelInput, OpenPaymentChannelOutput } from "../dto/channel.dto";
export interface ChannelRepository {
  listPaymentChannels(input: ListPaymentChannelsInput): Promise<ListPaymentChannelsOutput>;
  openPaymentChannel(input: OpenPaymentChannelInput): Promise<OpenPaymentChannelOutput>;
  getPaymentChannel(input: GetPaymentChannelInput): Promise<GetPaymentChannelOutput>;
}

export type { GetPaymentChannelInput, GetPaymentChannelOutput, ListPaymentChannelsInput, ListPaymentChannelsOutput, OpenPaymentChannelInput, OpenPaymentChannelOutput } from "../dto/channel.dto";
