/**
 * DiscoveryRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiscoveryRepository Port
 *
 * DDD: Application port for discoveryrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DiscoverPaymentChannelsInput, DiscoverPaymentChannelsOutput } from "../dto/discovery.dto";
export interface DiscoveryRepository {
  discoverPaymentChannels(input: DiscoverPaymentChannelsInput): Promise<DiscoverPaymentChannelsOutput>;
}

export type { DiscoverPaymentChannelsInput, DiscoverPaymentChannelsOutput } from "../dto/discovery.dto";
