/**
 * Channels DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Channels Domain Module - Composition root
 *
 * DDD: Composition root for channels domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ChannelRepositoryAdapter,
  CloseRepositoryAdapter,
  DiscoveryRepositoryAdapter,
} from "@hopsettle/adapters/channels";
import { getIdGeneratorService } from "@hopsettle/adapters";
import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteClosePaymentChannel,
  ExecuteDiscoverPaymentChannels,
  ExecuteGetPaymentChannel,
  ExecuteListPaymentChannels,
  ExecuteOpenPaymentChannel,
} from "@hopsettle/services/channels/usecases";
// Ports (interfaces)
import type {
  ChannelRepository,
  CloseRepository,
  DiscoveryRepository,
} from "@hopsettle/services/channels/ports";

export interface ChannelsDomainModule {
  repos: {
    channels: ChannelRepository;
    closes: CloseRepository;
    discoveries: DiscoveryRepository;
  };
  useCases: {
    channels: {
      get: ExecuteGetPaymentChannel;
      list: ExecuteListPaymentChannels;
    };
    closes: {
      get: ExecuteClosePaymentChannel;
    };
    discoveries: {
      get: ExecuteDiscoverPaymentChannels;
    };
  };
}

export function buildChannelsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ChannelsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      channels?: ChannelRepository;
      closes?: CloseRepository;
      discoveries?: DiscoveryRepository;
    } = {};

    obj.channels = new ChannelRepositoryAdapter(dynamoClient);
    obj.closes = new CloseRepositoryAdapter(dynamoClient);
    obj.discoveries = new DiscoveryRepositoryAdapter(dynamoClient);
    return {
      channels: obj.channels!,
      closes: obj.closes!,
      discoveries: obj.discoveries!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    channels: {
      get: new ExecuteGetPaymentChannel(executionContext, idGenerator, repos.channels),
      list: new ExecuteListPaymentChannels(executionContext, idGenerator, repos.channels),
    },
    closes: {
      get: new ExecuteClosePaymentChannel(executionContext, idGenerator, repos.closes),
    },
    discoveries: {
      get: new ExecuteDiscoverPaymentChannels(executionContext, idGenerator, repos.discoveries),
    },
  };
  return { repos, useCases: useCases as ChannelsDomainModule["useCases"] };
}
