/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @hopsettle/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@hopsettle/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@hopsettle/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@hopsettle/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@hopsettle/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@hopsettle/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _accounting from "./accounting/index.js";
import * as _channels from "./channels/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _pricing from "./pricing/index.js";
import * as _reporting from "./reporting/index.js";
import * as _settlement from "./settlement/index.js";
import * as _staking from "./staking/index.js";
import * as _topology from "./topology/index.js";

// Export as namespaces
export const _shared = __shared;
export const accounting = _accounting;
export const channels = _channels;
export const disputes = _disputes;
export const identity = _identity;
export const pricing = _pricing;
export const reporting = _reporting;
export const settlement = _settlement;
export const staking = _staking;
export const topology = _topology;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@hopsettle/core"; activity.types.*
//   - Direct exports: import * from "@hopsettle/core/activity/types/index.js"
//   - Direct exports: import * from "@hopsettle/core/activity/repositories/index.js"
//   - Direct exports: import * from "@hopsettle/core/activity/models/index.js"
//   - Direct exports: import * from "@hopsettle/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Accounting Service
export { schemas as AccountingSchemas } from "./accounting/schemas/accounting.schemas.js";

// Channels Service
export { schemas as ChannelsSchemas } from "./channels/schemas/channels.schemas.js";

// Disputes Service
export { schemas as DisputesSchemas } from "./disputes/schemas/disputes.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Pricing Service
export { schemas as PricingSchemas } from "./pricing/schemas/pricing.schemas.js";

// Reporting Service
export { schemas as ReportingSchemas } from "./reporting/schemas/reporting.schemas.js";

// Settlement Service
export { schemas as SettlementSchemas } from "./settlement/schemas/settlement.schemas.js";

// Staking Service
export { schemas as StakingSchemas } from "./staking/schemas/staking.schemas.js";

// Topology Service
export { schemas as TopologySchemas } from "./topology/schemas/topology.schemas.js";

