/**
 * ChannelReconciliation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChannelReconciliation DTOs
 *
 * DDD: Application DTOs for ChannelReconciliation use cases.
 */

import type { GetChannelReconciliationReportParams } from "@hopsettle/core/reporting/types";

export type GetChannelReconciliationReportInput = GetChannelReconciliationReportParams;

export type GetChannelReconciliationReportOutput = {};
