/**
 * RelayAttribution DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RelayAttribution DTOs
 *
 * DDD: Application DTOs for RelayAttribution use cases.
 */

import type { GetRelayAttributionReportParams } from "@hopsettle/core/reporting/types";

export type GetRelayAttributionReportInput = GetRelayAttributionReportParams;

export type GetRelayAttributionReportOutput = {};
