/**
 * Topology DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Topology Domain Module - Composition root
 *
 * DDD: Composition root for topology domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttachmentRepositoryAdapter,
  QuarantineRepositoryAdapter,
  ReleaseRepositoryAdapter,
  SnapshotRepositoryAdapter,
} from "@hopsettle/adapters/topology";
import { getIdGeneratorService } from "@hopsettle/adapters";
import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetTopologySnapshot,
  ExecuteListMeshAttachments,
  ExecuteListQuarantineRecords,
  ExecuteQuarantineMeshNode,
  ExecuteReleaseQuarantine,
} from "@hopsettle/services/topology/usecases";
// Ports (interfaces)
import type {
  AttachmentRepository,
  QuarantineRepository,
  ReleaseRepository,
  SnapshotRepository,
} from "@hopsettle/services/topology/ports";

export interface TopologyDomainModule {
  repos: {
    attachments: AttachmentRepository;
    quarantines: QuarantineRepository;
    releases: ReleaseRepository;
    snapshots: SnapshotRepository;
  };
  useCases: {
    attachments: {
      list: ExecuteListMeshAttachments;
    };
    quarantines: {
      get: ExecuteQuarantineMeshNode;
      list: ExecuteListQuarantineRecords;
    };
    releases: {
      get: ExecuteReleaseQuarantine;
    };
    snapshots: {
      get: ExecuteGetTopologySnapshot;
    };
  };
}

export function buildTopologyDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TopologyDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attachments?: AttachmentRepository;
      quarantines?: QuarantineRepository;
      releases?: ReleaseRepository;
      snapshots?: SnapshotRepository;
    } = {};

    obj.attachments = new AttachmentRepositoryAdapter(dynamoClient);
    obj.quarantines = new QuarantineRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    obj.snapshots = new SnapshotRepositoryAdapter(dynamoClient);
    return {
      attachments: obj.attachments!,
      quarantines: obj.quarantines!,
      releases: obj.releases!,
      snapshots: obj.snapshots!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    attachments: {
      list: new ExecuteListMeshAttachments(executionContext, idGenerator, repos.attachments),
    },
    quarantines: {
      get: new ExecuteQuarantineMeshNode(executionContext, idGenerator, repos.quarantines),
      list: new ExecuteListQuarantineRecords(executionContext, idGenerator, repos.quarantines),
    },
    releases: {
      get: new ExecuteReleaseQuarantine(executionContext, idGenerator, repos.releases),
    },
    snapshots: {
      get: new ExecuteGetTopologySnapshot(executionContext, idGenerator, repos.snapshots),
    },
  };
  return { repos, useCases: useCases as TopologyDomainModule["useCases"] };
}
