/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Staking Domain Use Cases
 * 
 * List of all use case names for the staking domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const STAKING_USE_CASES = [
  "executeGetStakingAccount",
  "executeListFloatAlerts",
  "executePauseNewChannelOffers",
  "executeRecordStakingTopUp"
] as const;
