/**
 * ExecuteRecordStakingTopUp - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordStakingTopUp Use Case
 *
 * DDD: Application use case for get TopUp.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordStakingTopUpInput, RecordStakingTopUpOutput } from "../dto/top-up.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { TopUpRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordStakingTopUp {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly topUp: TopUpRepository
  ) {}

  async execute(input: RecordStakingTopUpInput): Promise<RecordStakingTopUpOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stkId();

    // All field names extracted from OpenAPI spec: amountRmesh, note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).meshId) {
      throw new ValidationError("meshId is required");
    }
    const meshId = (input as any).meshId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.topUp.recordStakingTopUp({ meshId: meshId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${meshId}`);
    }

    return entity as RecordStakingTopUpOutput;
  }
}
