/**
 * ExecutePauseNewChannelOffers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePauseNewChannelOffers Use Case
 *
 * DDD: Application use case for get PauseOffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PauseNewChannelOffersInput, PauseNewChannelOffersOutput } from "../dto/pause-offer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { PauseOfferRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePauseNewChannelOffers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pauseOffer: PauseOfferRepository
  ) {}

  async execute(input: PauseNewChannelOffersInput): Promise<PauseNewChannelOffersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stkId();

    // All field names extracted from OpenAPI spec: paused, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).meshId) {
      throw new ValidationError("meshId is required");
    }
    const meshId = (input as any).meshId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.pauseOffer.pauseNewChannelOffers({ meshId: meshId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${meshId}`);
    }

    return entity as PauseNewChannelOffersOutput;
  }
}
