/**
 * ExecuteListFloatAlerts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFloatAlerts Use Case
 *
 * DDD: Application use case for list Alert.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFloatAlertsInput, ListFloatAlertsOutput } from "../dto/alert.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { AlertRepository } from "../ports";

export class ExecuteListFloatAlerts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alert: AlertRepository
  ) {}

  async execute(input: ListFloatAlertsInput): Promise<ListFloatAlertsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stkId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.alert.listFloatAlerts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFloatAlertsOutput;
  }
}
