/**
 * Channel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Channel DTOs
 *
 * DDD: Application DTOs for Channel use cases.
 */

import type { GetPaymentChannelParams, ListPaymentChannelsParams, OpenPaymentChannelRequestInput } from "@hopsettle/core/channels/types";

export type ListPaymentChannelsInput = ListPaymentChannelsParams;

export type OpenPaymentChannelInput = OpenPaymentChannelRequestInput;

export type GetPaymentChannelInput = GetPaymentChannelParams;

export type ListPaymentChannelsOutput = {};

export type OpenPaymentChannelOutput = {};

export type GetPaymentChannelOutput = {};
