/**
 * Discovery DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Discovery DTOs
 *
 * DDD: Application DTOs for Discovery use cases.
 */

import type { DiscoverPaymentChannelsRequestInput } from "@hopsettle/core/channels/types";

export type DiscoverPaymentChannelsInput = DiscoverPaymentChannelsRequestInput;

export type DiscoverPaymentChannelsOutput = {};
