/**
 * ChannelReconciliationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChannelReconciliationRepository Port
 *
 * DDD: Application port for channelreconciliationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetChannelReconciliationReportInput, GetChannelReconciliationReportOutput } from "../dto/channel-reconciliation.dto";
export interface ChannelReconciliationRepository {
  getChannelReconciliationReport(input: GetChannelReconciliationReportInput): Promise<GetChannelReconciliationReportOutput>;
}

export type { GetChannelReconciliationReportInput, GetChannelReconciliationReportOutput } from "../dto/channel-reconciliation.dto";
