/**
 * RelayAttributionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RelayAttributionRepository Port
 *
 * DDD: Application port for relayattributionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRelayAttributionReportInput, GetRelayAttributionReportOutput } from "../dto/relay-attribution.dto";
export interface RelayAttributionRepository {
  getRelayAttributionReport(input: GetRelayAttributionReportInput): Promise<GetRelayAttributionReportOutput>;
}

export type { GetRelayAttributionReportInput, GetRelayAttributionReportOutput } from "../dto/relay-attribution.dto";
