/**
 * Pricing DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pricing Domain Module - Composition root
 *
 * DDD: Composition root for pricing domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PathPreviewRepositoryAdapter,
  PolicyRepositoryAdapter,
} from "@hopsettle/adapters/pricing";
import { getIdGeneratorService } from "@hopsettle/adapters";
import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreatePricingPolicy,
  ExecuteGetPricingPolicy,
  ExecuteListPricingPolicies,
  ExecutePreviewPathCharges,
} from "@hopsettle/services/pricing/usecases";
// Ports (interfaces)
import type {
  PathPreviewRepository,
  PolicyRepository,
} from "@hopsettle/services/pricing/ports";

export interface PricingDomainModule {
  repos: {
    pathPreviews: PathPreviewRepository;
    policies: PolicyRepository;
  };
  useCases: {
    pathPreviews: {
      get: ExecutePreviewPathCharges;
    };
    policies: {
      create: ExecuteCreatePricingPolicy;
      get: ExecuteGetPricingPolicy;
      list: ExecuteListPricingPolicies;
    };
  };
}

export function buildPricingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PricingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      pathPreviews?: PathPreviewRepository;
      policies?: PolicyRepository;
    } = {};

    obj.pathPreviews = new PathPreviewRepositoryAdapter(dynamoClient);
    obj.policies = new PolicyRepositoryAdapter(dynamoClient);
    return {
      pathPreviews: obj.pathPreviews!,
      policies: obj.policies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    pathPreviews: {
      get: new ExecutePreviewPathCharges(executionContext, idGenerator, repos.pathPreviews),
    },
    policies: {
      create: new ExecuteCreatePricingPolicy(executionContext, idGenerator, repos.policies),
      get: new ExecuteGetPricingPolicy(executionContext, idGenerator, repos.policies),
      list: new ExecuteListPricingPolicies(executionContext, idGenerator, repos.policies),
    },
  };
  return { repos, useCases: useCases as PricingDomainModule["useCases"] };
}
