/**
 * ListEvidenceExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ExportDisputeEvidenceParams } from "@hopsettle/core/disputes";

export function createListEvidenceExportRequest(overrides: Partial<ExportDisputeEvidenceParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
