/**
 * GetStakingAccount handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getStakingAccount } from "@hopsettle/api-server/domains/staking/handlers";
import type { StakingDDDDependencies } from "@hopsettle/api-server/domains/staking";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@hopsettle/tests/shared";
import { STAKING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetStakingAccount", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: StakingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<StakingDDDDependencies>(
      STAKING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetStakingAccount, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { meshId: entity.id };

    await getStakingAccount(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetStakingAccount.execute).toHaveBeenCalledWith(expect.objectContaining({ meshId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { meshId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetStakingAccount, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getStakingAccount(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
