/**
 * Handlers for Policy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PricingDomainModule } from "../dependencies/pricing-ddd.dependencies.js";
import type { CreatePricingPolicyInput, GetPricingPolicyInput, ListPricingPoliciesInput } from "@hopsettle/services/pricing";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/pricing/policies
 * Operation: listPricingPolicies
 */
export async function listPricingPolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { role?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PricingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPricingPoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.policies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/pricing/policies
 * Operation: createPricingPolicy
 */
export async function createPricingPolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PricingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePricingPolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/pricing/policies/{policyId}
 * Operation: getPricingPolicy
 */
export async function getPricingPolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PricingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPricingPolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.policies.get.execute(input);
  return reply.code(200).send(result);
}


