/**
 * ExecuteIngestAccountingEntry - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIngestAccountingEntry Use Case
 *
 * DDD: Application use case for get AccountingEntry.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IngestAccountingEntryInput, IngestAccountingEntryOutput } from "../dto/accounting-entry.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { AccountingEntryRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIngestAccountingEntry {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly accountingEntry: AccountingEntryRepository
  ) {}

  async execute(input: IngestAccountingEntryInput): Promise<IngestAccountingEntryOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.acctId();

    // All field names extracted from OpenAPI spec: balanceDeltaRmesh, bpsSignature, bytes, channelId, chsSignature, packetId, packetType, relayMeshId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).channelId) {
      throw new ValidationError("channelId is required");
    }
    const channelId = (input as any).channelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.accountingEntry.ingestAccountingEntry({ channelId: channelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${channelId}`);
    }

    return entity as IngestAccountingEntryOutput;
  }
}
