/**
 * ExecuteListAccountingEntries - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAccountingEntries Use Case
 *
 * DDD: Application use case for list AccountingEntry.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAccountingEntriesInput, ListAccountingEntriesOutput } from "../dto/accounting-entry.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { AccountingEntryRepository } from "../ports";

export class ExecuteListAccountingEntries {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly accountingEntry: AccountingEntryRepository
  ) {}

  async execute(input: ListAccountingEntriesInput): Promise<ListAccountingEntriesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.acctId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.accountingEntry.listAccountingEntries({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAccountingEntriesOutput;
  }
}
