/**
 * ExecuteMarkAccountingEntryReviewed - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteMarkAccountingEntryReviewed Use Case
 *
 * DDD: Application use case for get Review.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { MarkAccountingEntryReviewedInput, MarkAccountingEntryReviewedOutput } from "../dto/review.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { ReviewRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteMarkAccountingEntryReviewed {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly review: ReviewRepository
  ) {}

  async execute(input: MarkAccountingEntryReviewedInput): Promise<MarkAccountingEntryReviewedOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.acctId();

    // All field names extracted from OpenAPI spec: note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).entryId) {
      throw new ValidationError("entryId is required");
    }
    const entryId = (input as any).entryId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.review.markAccountingEntryReviewed({ entryId: entryId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${entryId}`);
    }

    return entity as MarkAccountingEntryReviewedOutput;
  }
}
