/**
 * Accounting Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const ingestAccountingEntry_Body = z
  .object({
    channelId: z.string(),
    packetId: z.string().optional(),
    packetType: z.enum(['DATA', 'DATA_ACK']),
    bytes: z.number().int().gte(0),
    bpsSignature: z.string(),
    chsSignature: z.string().optional(),
    balanceDeltaRmesh: z.number().optional(),
    relayMeshId: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  ingestAccountingEntry_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/accounting/entries',
    alias: 'listAccountingEntries',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'channelId',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'reconcileStatus',
        type: 'Query',
        schema: z
          .enum([
            'pending',
            'within_tolerance',
            'diverged',
            'reviewed',
            'quarantined',
          ])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  entryId: z.string().regex(/^ace_[0-9A-HJKMNP-TV-Z]{26}$/),
                  channelId: z.string(),
                  packetId: z.string().optional(),
                  packetType: z.enum(['DATA', 'DATA_ACK']),
                  bytes: z.number().int().gte(0),
                  bpsSignature: z.string(),
                  chsSignature: z.string().optional(),
                  balanceDeltaRmesh: z.number().optional(),
                  reconcileStatus: z.enum([
                    'pending',
                    'within_tolerance',
                    'diverged',
                    'reviewed',
                    'quarantined',
                  ]),
                  toleranceBps: z.number().optional(),
                  relayMeshId: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
            mismatchRate: z.number().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/accounting/entries',
    alias: 'ingestAccountingEntry',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: ingestAccountingEntry_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            entryId: z.string().regex(/^ace_[0-9A-HJKMNP-TV-Z]{26}$/),
            channelId: z.string(),
            packetId: z.string().optional(),
            packetType: z.enum(['DATA', 'DATA_ACK']),
            bytes: z.number().int().gte(0),
            bpsSignature: z.string(),
            chsSignature: z.string().optional(),
            balanceDeltaRmesh: z.number().optional(),
            reconcileStatus: z.enum([
              'pending',
              'within_tolerance',
              'diverged',
              'reviewed',
              'quarantined',
            ]),
            toleranceBps: z.number().optional(),
            relayMeshId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/accounting/entries/:entryId/review',
    alias: 'markAccountingEntryReviewed',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: z
          .object({ note: z.string().max(1000) })
          .partial()
          .passthrough(),
      },
      {
        name: 'entryId',
        type: 'Path',
        schema: z.string().regex(/^ace_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            entryId: z.string().regex(/^ace_[0-9A-HJKMNP-TV-Z]{26}$/),
            channelId: z.string(),
            packetId: z.string().optional(),
            packetType: z.enum(['DATA', 'DATA_ACK']),
            bytes: z.number().int().gte(0),
            bpsSignature: z.string(),
            chsSignature: z.string().optional(),
            balanceDeltaRmesh: z.number().optional(),
            reconcileStatus: z.enum([
              'pending',
              'within_tolerance',
              'diverged',
              'reviewed',
              'quarantined',
            ]),
            toleranceBps: z.number().optional(),
            relayMeshId: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
