/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { channelReconciliationRoutes } from "./channel-reconciliation.routes.js";
export { relayAttributionRoutes } from "./relay-attribution.routes.js";
