/**
 * AccountingEntryRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccountingEntryRepository Port
 *
 * DDD: Application port for accountingentryrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestAccountingEntryInput, IngestAccountingEntryOutput, ListAccountingEntriesInput, ListAccountingEntriesOutput } from "../dto/accounting-entry.dto";
export interface AccountingEntryRepository {
  listAccountingEntries(input: ListAccountingEntriesInput): Promise<ListAccountingEntriesOutput>;
  ingestAccountingEntry(input: IngestAccountingEntryInput): Promise<IngestAccountingEntryOutput>;
}

export type { IngestAccountingEntryInput, IngestAccountingEntryOutput, ListAccountingEntriesInput, ListAccountingEntriesOutput } from "../dto/accounting-entry.dto";
