/**
 * Statement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Statement DTOs
 *
 * DDD: Application DTOs for Statement use cases.
 */

import type { GetSettlementStatementParams, ListSettlementStatementsParams } from "@hopsettle/core/settlement/types";

export type ListSettlementStatementsInput = ListSettlementStatementsParams;

export type GetSettlementStatementInput = GetSettlementStatementParams;

export type ListSettlementStatementsOutput = {};

export type GetSettlementStatementOutput = {};
