/**
 * Reporting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reporting Domain Module - Composition root
 *
 * DDD: Composition root for reporting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ChannelReconciliationRepositoryAdapter,
  RelayAttributionRepositoryAdapter,
} from "@hopsettle/adapters/reporting";
import { getIdGeneratorService } from "@hopsettle/adapters";
import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetChannelReconciliationReport,
  ExecuteGetRelayAttributionReport,
} from "@hopsettle/services/reporting/usecases";
// Ports (interfaces)
import type {
  ChannelReconciliationRepository,
  RelayAttributionRepository,
} from "@hopsettle/services/reporting/ports";

export interface ReportingDomainModule {
  repos: {
    channelReconciliations: ChannelReconciliationRepository;
    relayAttributions: RelayAttributionRepository;
  };
  useCases: {
    channelReconciliations: {
      get: ExecuteGetChannelReconciliationReport;
    };
    relayAttributions: {
      get: ExecuteGetRelayAttributionReport;
    };
  };
}

export function buildReportingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      channelReconciliations?: ChannelReconciliationRepository;
      relayAttributions?: RelayAttributionRepository;
    } = {};

    obj.channelReconciliations = new ChannelReconciliationRepositoryAdapter(dynamoClient);
    obj.relayAttributions = new RelayAttributionRepositoryAdapter(dynamoClient);
    return {
      channelReconciliations: obj.channelReconciliations!,
      relayAttributions: obj.relayAttributions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    channelReconciliations: {
      get: new ExecuteGetChannelReconciliationReport(executionContext, idGenerator, repos.channelReconciliations),
    },
    relayAttributions: {
      get: new ExecuteGetRelayAttributionReport(executionContext, idGenerator, repos.relayAttributions),
    },
  };
  return { repos, useCases: useCases as ReportingDomainModule["useCases"] };
}
