/**
 * Alert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alert DTOs
 *
 * DDD: Application DTOs for Alert use cases.
 */

import type { ListFloatAlertsParams } from "@hopsettle/core/staking/types";

export type ListFloatAlertsInput = ListFloatAlertsParams;

export type ListFloatAlertsOutput = {};
