/**
 * PauseOffer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PauseOffer DTOs
 *
 * DDD: Application DTOs for PauseOffer use cases.
 */

import type { PauseNewChannelOffersParams, PauseNewChannelOffersRequestInput } from "@hopsettle/core/staking/types";

export type PauseNewChannelOffersInput = PauseNewChannelOffersParams & PauseNewChannelOffersRequestInput;

export type PauseNewChannelOffersOutput = {};
