/**
 * TopUp DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TopUp DTOs
 *
 * DDD: Application DTOs for TopUp use cases.
 */

import type { RecordStakingTopUpParams, RecordStakingTopUpRequestInput } from "@hopsettle/core/staking/types";

export type RecordStakingTopUpInput = RecordStakingTopUpParams & RecordStakingTopUpRequestInput;

export type RecordStakingTopUpOutput = {};
