/**
 * ExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepository Port
 *
 * DDD: Application port for exportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExportSettlementStatementInput, ExportSettlementStatementOutput } from "../dto/export.dto";
export interface ExportRepository {
  exportSettlementStatement(input: ExportSettlementStatementInput): Promise<ExportSettlementStatementOutput>;
}

export type { ExportSettlementStatementInput, ExportSettlementStatementOutput } from "../dto/export.dto";
