/**
 * GetPolicy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetPricingPolicyParams } from "@hopsettle/core/pricing";

export function createGetPolicyRequest(overrides: Partial<GetPricingPolicyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
