/**
 * TopUpRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TopUpRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TopUpRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TopUpRepository,
} from "@hopsettle/services/staking";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TopUpRepositoryDdb } from "./top-up-repository.ddb.js";

/**
 * TopUpRepositoryAdapter
 *
 * Implements TopUpRepository port for infrastructure layer.
 */
export class TopUpRepositoryAdapter implements TopUpRepository {
  private readonly ddb: TopUpRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TopUpRepositoryDdb(this.dynamoClient);
  }

  async recordStakingTopUp(input: Parameters<TopUpRepository['recordStakingTopUp']>[0]): Promise<Awaited<ReturnType<TopUpRepository['recordStakingTopUp']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordStakingTopUp(input);
  }
}
