/**
 * ChannelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ChannelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ChannelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ChannelRepository,
} from "@hopsettle/services/channels";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ChannelRepositoryDdb } from "./channel-repository.ddb.js";

/**
 * ChannelRepositoryAdapter
 *
 * Implements ChannelRepository port for infrastructure layer.
 */
export class ChannelRepositoryAdapter implements ChannelRepository {
  private readonly ddb: ChannelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ChannelRepositoryDdb(this.dynamoClient);
  }

  async listPaymentChannels(input: Parameters<ChannelRepository['listPaymentChannels']>[0]): Promise<Awaited<ReturnType<ChannelRepository['listPaymentChannels']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPaymentChannels(input);
  }

  async openPaymentChannel(input: Parameters<ChannelRepository['openPaymentChannel']>[0]): Promise<Awaited<ReturnType<ChannelRepository['openPaymentChannel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openPaymentChannel(input);
  }

  async getPaymentChannel(input: Parameters<ChannelRepository['getPaymentChannel']>[0]): Promise<Awaited<ReturnType<ChannelRepository['getPaymentChannel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPaymentChannel(input);
  }
}
