/**
 * DiscoveryRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiscoveryRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DiscoveryRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DiscoveryRepository,
} from "@hopsettle/services/channels";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DiscoveryRepositoryDdb } from "./discovery-repository.ddb.js";

/**
 * DiscoveryRepositoryAdapter
 *
 * Implements DiscoveryRepository port for infrastructure layer.
 */
export class DiscoveryRepositoryAdapter implements DiscoveryRepository {
  private readonly ddb: DiscoveryRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DiscoveryRepositoryDdb(this.dynamoClient);
  }

  async discoverPaymentChannels(input: Parameters<DiscoveryRepository['discoverPaymentChannels']>[0]): Promise<Awaited<ReturnType<DiscoveryRepository['discoverPaymentChannels']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.discoverPaymentChannels(input);
  }
}
