/**
 * GetChannel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetPaymentChannelParams } from "@hopsettle/core/channels";

export function createGetChannelRequest(overrides: Partial<GetPaymentChannelParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
