/**
 * Handlers for Quarantine
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TopologyDomainModule } from "../dependencies/topology-ddd.dependencies.js";
import type { ListQuarantineRecordsInput, QuarantineMeshNodeInput } from "@hopsettle/services/topology";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/topology/quarantine
 * Operation: listQuarantineRecords
 */
export async function listQuarantineRecords(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TopologyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListQuarantineRecordsInput = {};
  const result = await deps.useCases.quarantines.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/topology/quarantine/{meshId}
 * Operation: quarantineMeshNode
 */
export async function quarantineMeshNode(
  request: FastifyRequest<{ Params: { meshId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TopologyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: QuarantineMeshNodeInput = {
    meshId: request.params.meshId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.quarantines.get.execute(input);
  return reply.code(200).send(result);
}


