/**
 * Handlers for Snapshot
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TopologyDomainModule } from "../dependencies/topology-ddd.dependencies.js";
import type { GetTopologySnapshotInput } from "@hopsettle/services/topology";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/topology/snapshot
 * Operation: getTopologySnapshot
 */
export async function getTopologySnapshot(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { attachmentId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TopologyDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetTopologySnapshotInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.snapshots.get.execute(input);
  return reply.code(200).send(result);
}


