/**
 * ExecuteQuarantineMeshNode - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteQuarantineMeshNode Use Case
 *
 * DDD: Application use case for get Quarantine.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { QuarantineMeshNodeInput, QuarantineMeshNodeOutput } from "../dto/quarantine.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { QuarantineRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteQuarantineMeshNode {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly quarantine: QuarantineRepository
  ) {}

  async execute(input: QuarantineMeshNodeInput): Promise<QuarantineMeshNodeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.topoId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).meshId) {
      throw new ValidationError("meshId is required");
    }
    const meshId = (input as any).meshId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.quarantine.quarantineMeshNode({ meshId: meshId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${meshId}`);
    }

    return entity as QuarantineMeshNodeOutput;
  }
}
