/**
 * ExecuteListQuarantineRecords - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListQuarantineRecords Use Case
 *
 * DDD: Application use case for list Quarantine.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListQuarantineRecordsInput, ListQuarantineRecordsOutput } from "../dto/quarantine.dto";
import type { ExecutionContextService, IdGeneratorService } from "@hopsettle/services/_shared/index.js";
import type { QuarantineRepository } from "../ports";

export class ExecuteListQuarantineRecords {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly quarantine: QuarantineRepository
  ) {}

  async execute(input: ListQuarantineRecordsInput): Promise<ListQuarantineRecordsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.topoId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.quarantine.listQuarantineRecords({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListQuarantineRecordsOutput;
  }
}
