/**
 * StatementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StatementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements StatementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  StatementRepository,
} from "@hopsettle/services/settlement";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { StatementRepositoryDdb } from "./statement-repository.ddb.js";

/**
 * StatementRepositoryAdapter
 *
 * Implements StatementRepository port for infrastructure layer.
 */
export class StatementRepositoryAdapter implements StatementRepository {
  private readonly ddb: StatementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new StatementRepositoryDdb(this.dynamoClient);
  }

  async listSettlementStatements(input: Parameters<StatementRepository['listSettlementStatements']>[0]): Promise<Awaited<ReturnType<StatementRepository['listSettlementStatements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSettlementStatements(input);
  }

  async getSettlementStatement(input: Parameters<StatementRepository['getSettlementStatement']>[0]): Promise<Awaited<ReturnType<StatementRepository['getSettlementStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSettlementStatement(input);
  }
}
