/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: topology
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@hopsettle/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@hopsettle/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@hopsettle/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _accounting from "./accounting/index.js";
import * as _channels from "./channels/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _pricing from "./pricing/index.js";
import * as _reporting from "./reporting/index.js";
import * as _settlement from "./settlement/index.js";
import * as _staking from "./staking/index.js";
import * as _topology from "./topology/index.js";

// Export as namespaces
export const accounting = _accounting;
export const channels = _channels;
export const disputes = _disputes;
export const identity = _identity;
export const pricing = _pricing;
export const reporting = _reporting;
export const settlement = _settlement;
export const staking = _staking;
export const topology = _topology;
