/**
 * Routes for EvidenceExport
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { exportDisputeEvidence } from "../handlers/evidence-export.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function evidenceExportRoutes(fastify: FastifyInstance) {
  // POST /v1/disputes/{disputeId}/evidence-export (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/disputes/:disputeId/evidence-export",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { disputeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDisputesDependenciesForRequest();
        await exportDisputeEvidence(request, reply, deps);
      });
    }
  );


}
