/**
 * PathPreviewRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PathPreviewRepositoryDdb
 *
 * DDD: Infrastructure adapter for PathPreview repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { PathPreviewRepository } from "@hopsettle/services/pricing";

export class PathPreviewRepositoryDdb implements PathPreviewRepository {
  constructor(private readonly dynamoClient: any) {}

  async previewPathCharges(input: Parameters<PathPreviewRepository['previewPathCharges']>[0]): Promise<Awaited<ReturnType<PathPreviewRepository['previewPathCharges']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
