/**
 * PathPreviewRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PathPreviewRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PathPreviewRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PathPreviewRepository,
} from "@hopsettle/services/pricing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PathPreviewRepositoryDdb } from "./path-preview-repository.ddb.js";

/**
 * PathPreviewRepositoryAdapter
 *
 * Implements PathPreviewRepository port for infrastructure layer.
 */
export class PathPreviewRepositoryAdapter implements PathPreviewRepository {
  private readonly ddb: PathPreviewRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PathPreviewRepositoryDdb(this.dynamoClient);
  }

  async previewPathCharges(input: Parameters<PathPreviewRepository['previewPathCharges']>[0]): Promise<Awaited<ReturnType<PathPreviewRepository['previewPathCharges']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.previewPathCharges(input);
  }
}
