/**
 * PolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PolicyRepository,
} from "@hopsettle/services/pricing";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PolicyRepositoryDdb } from "./policy-repository.ddb.js";

/**
 * PolicyRepositoryAdapter
 *
 * Implements PolicyRepository port for infrastructure layer.
 */
export class PolicyRepositoryAdapter implements PolicyRepository {
  private readonly ddb: PolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PolicyRepositoryDdb(this.dynamoClient);
  }

  async listPricingPolicies(input: Parameters<PolicyRepository['listPricingPolicies']>[0]): Promise<Awaited<ReturnType<PolicyRepository['listPricingPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPricingPolicies(input);
  }

  async createPricingPolicy(input: Parameters<PolicyRepository['createPricingPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['createPricingPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPricingPolicy(input);
  }

  async getPricingPolicy(input: Parameters<PolicyRepository['getPricingPolicy']>[0]): Promise<Awaited<ReturnType<PolicyRepository['getPricingPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPricingPolicy(input);
  }
}
