/**
 * Handlers for Review
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AccountingDomainModule } from "../dependencies/accounting-ddd.dependencies.js";
import type { MarkAccountingEntryReviewedInput } from "@hopsettle/services/accounting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/accounting/entries/{entryId}/review
 * Operation: markAccountingEntryReviewed
 */
export async function markAccountingEntryReviewed(
  request: FastifyRequest<{ Params: { entryId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AccountingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: MarkAccountingEntryReviewedInput = {
    entryId: request.params.entryId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reviews.get.execute(input);
  return reply.code(200).send(result);
}


