/**
 * Disputes DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disputes Domain Module - Composition root
 *
 * DDD: Composition root for disputes domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisputeRepositoryAdapter,
  EvidenceExportRepositoryAdapter,
  ResolveRepositoryAdapter,
} from "@hopsettle/adapters/disputes";
import { getIdGeneratorService } from "@hopsettle/adapters";
import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateDispute,
  ExecuteExportDisputeEvidence,
  ExecuteGetDispute,
  ExecuteListDisputes,
  ExecuteResolveDispute,
} from "@hopsettle/services/disputes/usecases";
// Ports (interfaces)
import type {
  DisputeRepository,
  EvidenceExportRepository,
  ResolveRepository,
} from "@hopsettle/services/disputes/ports";

export interface DisputesDomainModule {
  repos: {
    disputes: DisputeRepository;
    evidenceExports: EvidenceExportRepository;
    resolves: ResolveRepository;
  };
  useCases: {
    disputes: {
      create: ExecuteCreateDispute;
      get: ExecuteGetDispute;
      list: ExecuteListDisputes;
    };
    evidenceExports: {
      list: ExecuteExportDisputeEvidence;
    };
    resolves: {
      get: ExecuteResolveDispute;
    };
  };
}

export function buildDisputesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DisputesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disputes?: DisputeRepository;
      evidenceExports?: EvidenceExportRepository;
      resolves?: ResolveRepository;
    } = {};

    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.evidenceExports = new EvidenceExportRepositoryAdapter(dynamoClient);
    obj.resolves = new ResolveRepositoryAdapter(dynamoClient);
    return {
      disputes: obj.disputes!,
      evidenceExports: obj.evidenceExports!,
      resolves: obj.resolves!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disputes: {
      create: new ExecuteCreateDispute(executionContext, idGenerator, repos.disputes),
      get: new ExecuteGetDispute(executionContext, idGenerator, repos.disputes),
      list: new ExecuteListDisputes(executionContext, idGenerator, repos.disputes),
    },
    evidenceExports: {
      list: new ExecuteExportDisputeEvidence(executionContext, idGenerator, repos.evidenceExports),
    },
    resolves: {
      get: new ExecuteResolveDispute(executionContext, idGenerator, repos.resolves),
    },
  };
  return { repos, useCases: useCases as DisputesDomainModule["useCases"] };
}
