/**
 * Pricing Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createPricingPolicy_Body = z
  .object({
    role: z.enum(['seller', 'superpeer', 'app_superpeer']),
    unit: z.enum(['per_mb', 'per_packet']),
    pricePerUnit: z.number().gte(0),
    superpeerMarkupPercent: z.number().gte(0).optional(),
    relaySharePercent: z.number().gte(0).optional(),
    meshAttachmentId: z.string().optional(),
    effectiveAt: z.string().datetime({ offset: true }).optional(),
  })
  .passthrough();
const previewPathCharges_Body = z
  .object({
    bytes: z.number().int().gte(1),
    policyId: z
      .string()
      .regex(/^prc_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    meshAttachmentId: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  createPricingPolicy_Body,
  previewPathCharges_Body,
};

const endpoints = makeApi([
  {
    method: 'post',
    path: '/v1/pricing/path-preview',
    alias: 'previewPathCharges',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: previewPathCharges_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            hops: z.array(
              z.object({ label: z.string(), rmesh: z.number() }).passthrough()
            ),
            totalRmesh: z.number(),
            sampleBytes: z.number().int().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/pricing/policies',
    alias: 'listPricingPolicies',
    requestFormat: 'json',
    parameters: [
      {
        name: 'role',
        type: 'Query',
        schema: z.enum(['seller', 'superpeer', 'app_superpeer']).optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['draft', 'active', 'scheduled', 'archived']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  policyId: z.string().regex(/^prc_[0-9A-HJKMNP-TV-Z]{26}$/),
                  role: z.enum(['seller', 'superpeer', 'app_superpeer']),
                  unit: z.enum(['per_mb', 'per_packet']),
                  pricePerUnit: z.number().gte(0),
                  superpeerMarkupPercent: z.number().gte(0).optional(),
                  relaySharePercent: z.number().gte(0).optional(),
                  meshAttachmentId: z.string().optional(),
                  status: z.enum(['draft', 'active', 'scheduled', 'archived']),
                  effectiveAt: z.string().datetime({ offset: true }).optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/pricing/policies',
    alias: 'createPricingPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createPricingPolicy_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            policyId: z.string().regex(/^prc_[0-9A-HJKMNP-TV-Z]{26}$/),
            role: z.enum(['seller', 'superpeer', 'app_superpeer']),
            unit: z.enum(['per_mb', 'per_packet']),
            pricePerUnit: z.number().gte(0),
            superpeerMarkupPercent: z.number().gte(0).optional(),
            relaySharePercent: z.number().gte(0).optional(),
            meshAttachmentId: z.string().optional(),
            status: z.enum(['draft', 'active', 'scheduled', 'archived']),
            effectiveAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/pricing/policies/:policyId',
    alias: 'getPricingPolicy',
    requestFormat: 'json',
    parameters: [
      {
        name: 'policyId',
        type: 'Path',
        schema: z.string().regex(/^prc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            policyId: z.string().regex(/^prc_[0-9A-HJKMNP-TV-Z]{26}$/),
            role: z.enum(['seller', 'superpeer', 'app_superpeer']),
            unit: z.enum(['per_mb', 'per_packet']),
            pricePerUnit: z.number().gte(0),
            superpeerMarkupPercent: z.number().gte(0).optional(),
            relaySharePercent: z.number().gte(0).optional(),
            meshAttachmentId: z.string().optional(),
            status: z.enum(['draft', 'active', 'scheduled', 'archived']),
            effectiveAt: z.string().datetime({ offset: true }).optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
