/**
 * PathPreviewRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PathPreviewRepository Port
 *
 * DDD: Application port for pathpreviewrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PreviewPathChargesInput, PreviewPathChargesOutput } from "../dto/path-preview.dto";
export interface PathPreviewRepository {
  previewPathCharges(input: PreviewPathChargesInput): Promise<PreviewPathChargesOutput>;
}

export type { PreviewPathChargesInput, PreviewPathChargesOutput } from "../dto/path-preview.dto";
