/**
 * ListAccountingEntry DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAccountingEntriesParams } from "@hopsettle/core/accounting";

export function createListAccountingEntryRequest(overrides: Partial<ListAccountingEntriesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
