/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: channels
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { discoveryRoutes } from "./discovery.routes.js";
export { channelRoutes } from "./channel.routes.js";
export { closeRoutes } from "./close.routes.js";
