/**
 * Routes for PauseOffer
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: staking
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { pauseNewChannelOffers } from "../handlers/pause-offer.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function pauseOfferRoutes(fastify: FastifyInstance) {
  // POST /v1/staking/accounts/{meshId}/pause-offers (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/staking/accounts/:meshId/pause-offers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { meshId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStakingDependenciesForRequest();
        await pauseNewChannelOffers(request, reply, deps);
      });
    }
  );


}
