/**
 * ListExport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ExportSettlementStatementParams } from "@hopsettle/core/settlement";

export function createListExportRequest(overrides: Partial<ExportSettlementStatementParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
