/**
 * PathPreview DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PathPreview DTOs
 *
 * DDD: Application DTOs for PathPreview use cases.
 */

import type { PreviewPathChargesRequestInput } from "@hopsettle/core/pricing/types";

export type PreviewPathChargesInput = PreviewPathChargesRequestInput;

export type PreviewPathChargesOutput = {};
