/**
 * Policy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Policy DTOs
 *
 * DDD: Application DTOs for Policy use cases.
 */

import type { CreatePricingPolicyRequestInput, GetPricingPolicyParams, ListPricingPoliciesParams } from "@hopsettle/core/pricing/types";

export type ListPricingPoliciesInput = ListPricingPoliciesParams;

export type CreatePricingPolicyInput = CreatePricingPolicyRequestInput;

export type GetPricingPolicyInput = GetPricingPolicyParams;

export type ListPricingPoliciesOutput = {};

export type CreatePricingPolicyOutput = {};

export type GetPricingPolicyOutput = {};
