/**
 * AccountingEntryRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccountingEntryRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AccountingEntryRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AccountingEntryRepository,
} from "@hopsettle/services/accounting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AccountingEntryRepositoryDdb } from "./accounting-entry-repository.ddb.js";

/**
 * AccountingEntryRepositoryAdapter
 *
 * Implements AccountingEntryRepository port for infrastructure layer.
 */
export class AccountingEntryRepositoryAdapter implements AccountingEntryRepository {
  private readonly ddb: AccountingEntryRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AccountingEntryRepositoryDdb(this.dynamoClient);
  }

  async listAccountingEntries(input: Parameters<AccountingEntryRepository['listAccountingEntries']>[0]): Promise<Awaited<ReturnType<AccountingEntryRepository['listAccountingEntries']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAccountingEntries(input);
  }

  async ingestAccountingEntry(input: Parameters<AccountingEntryRepository['ingestAccountingEntry']>[0]): Promise<Awaited<ReturnType<AccountingEntryRepository['ingestAccountingEntry']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestAccountingEntry(input);
  }
}
