/**
 * AccountingEntryRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccountingEntryRepositoryDdb
 *
 * DDD: Infrastructure adapter for AccountingEntry repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { AccountingEntryRepository } from "@hopsettle/services/accounting";

export class AccountingEntryRepositoryDdb implements AccountingEntryRepository {
  constructor(private readonly dynamoClient: any) {}

  async listAccountingEntries(input: Parameters<AccountingEntryRepository['listAccountingEntries']>[0]): Promise<Awaited<ReturnType<AccountingEntryRepository['listAccountingEntries']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }

  async ingestAccountingEntry(input: Parameters<AccountingEntryRepository['ingestAccountingEntry']>[0]): Promise<Awaited<ReturnType<AccountingEntryRepository['ingestAccountingEntry']>>> {
    // TODO: Implement using x-dynamodb metadata
    throw new Error("Not implemented - missing x-dynamodb metadata");
  }
}
