/**
 * ReviewRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: accounting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReviewRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReviewRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReviewRepository,
} from "@hopsettle/services/accounting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReviewRepositoryDdb } from "./review-repository.ddb.js";

/**
 * ReviewRepositoryAdapter
 *
 * Implements ReviewRepository port for infrastructure layer.
 */
export class ReviewRepositoryAdapter implements ReviewRepository {
  private readonly ddb: ReviewRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReviewRepositoryDdb(this.dynamoClient);
  }

  async markAccountingEntryReviewed(input: Parameters<ReviewRepository['markAccountingEntryReviewed']>[0]): Promise<Awaited<ReturnType<ReviewRepository['markAccountingEntryReviewed']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.markAccountingEntryReviewed(input);
  }
}
