/**
 * Settlement DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Settlement Domain Module - Composition root
 *
 * DDD: Composition root for settlement domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExportRepositoryAdapter,
  StatementRepositoryAdapter,
} from "@hopsettle/adapters/settlement";
import { getIdGeneratorService } from "@hopsettle/adapters";
import type { AdapterDynamoDBClient } from "@hopsettle/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExportSettlementStatement,
  ExecuteGetSettlementStatement,
  ExecuteListSettlementStatements,
} from "@hopsettle/services/settlement/usecases";
// Ports (interfaces)
import type {
  ExportRepository,
  StatementRepository,
} from "@hopsettle/services/settlement/ports";

export interface SettlementDomainModule {
  repos: {
    exports: ExportRepository;
    statements: StatementRepository;
  };
  useCases: {
    exports: {
      list: ExecuteExportSettlementStatement;
    };
    statements: {
      get: ExecuteGetSettlementStatement;
      list: ExecuteListSettlementStatements;
    };
  };
}

export function buildSettlementDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SettlementDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      exports?: ExportRepository;
      statements?: StatementRepository;
    } = {};

    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    obj.statements = new StatementRepositoryAdapter(dynamoClient);
    return {
      exports: obj.exports!,
      statements: obj.statements!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    exports: {
      list: new ExecuteExportSettlementStatement(executionContext, idGenerator, repos.exports),
    },
    statements: {
      get: new ExecuteGetSettlementStatement(executionContext, idGenerator, repos.statements),
      list: new ExecuteListSettlementStatements(executionContext, idGenerator, repos.statements),
    },
  };
  return { repos, useCases: useCases as SettlementDomainModule["useCases"] };
}
