/**
 * GetPricingPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pricing
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getPricingPolicy } from "@hopsettle/api-server/domains/pricing/handlers";
import type { PricingDDDDependencies } from "@hopsettle/api-server/domains/pricing";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@hopsettle/tests/shared";
import { PRICING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetPricingPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: PricingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<PricingDDDDependencies>(
      PRICING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetPricingPolicy, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { policyId: entity.id };

    await getPricingPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetPricingPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { policyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetPricingPolicy, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getPricingPolicy(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
